import fs from "node:fs";
const cards = JSON.parse(
  fs.readFileSync("src/data/tcgpCardsDatabase.json", "utf8"),
);
const rules = JSON.parse(
  fs.readFileSync("src/data/tradeRulesConfig.json", "utf8"),
);
const rows = cards.map((c) => ({
  id: c.id,
  rarity: c.rarity,
  eligible:
    rules.allowedRarities.includes(c.rarity) &&
    !(/^(PROMO|P-)/.test(c.id) || /^(PROMO|P-)/.test(c.expansionCode || "")),
}));
const sql =
  "-- Generated by npm run catalog:seed; review eligibility against the in-game trade list.\nbegin;\ninsert into public.card_catalog_v2(id,rarity,eligible)\nselect id,rarity,eligible from jsonb_to_recordset($catalog$" +
  JSON.stringify(rows) +
  "$catalog$::jsonb) as c(id text,rarity text,eligible boolean)\non conflict(id) do update set rarity=excluded.rarity,eligible=excluded.eligible;\ncommit;\n";
fs.writeFileSync("supabase/migrations/202610080002_card_catalog.sql", sql);
